onboarding = false

[theme]
name = "terminal"

[theme.custom]
panel_bg = "black"

[terminal]
# Use same directory while creating different file
new_cwd = "follow"

[keys]
prefix = "alt+space"

# Config and help
reload_config = "prefix+q"
help = "prefix+?"
detach = "prefix+d"

# Copy mode
copy_mode = "prefix+["

# Panes
split_horizontal = ["prefix+h", "shift+enter"]
split_vertical = ["prefix+v", "alt+enter"]
close_pane = ["prefix+x", "alt+esc"]
zoom = "prefix+z"
last_pane = "prefix+;"

focus_pane_left = "ctrl+alt+left"
focus_pane_down = "ctrl+alt+down"
focus_pane_up = "ctrl+alt+up"
focus_pane_right = "ctrl+alt+right"

resize_mode = ["prefix+{"]
resize_pane_left = ["prefix+shift+h" ,"ctrl+alt+shift+left" ]
resize_pane_down = ["prefix+shift+j", "ctrl+alt+shift+down" ]
resize_pane_up = ["prefix+shift+k", "ctrl+alt+shift+up" ]
resize_pane_right = ["prefix+shift+l", "ctrl+alt+shift+right" ]

rename_pane = "prefix+shift+o"

# Windows -> tabs
new_tab = "prefix+c"
rename_tab = "prefix+r"
close_tab = "prefix+shift+x"
switch_tab = ["prefix+1..9", "alt+1..9"]
previous_tab = ["prefix+p", "alt+left"]
next_tab = ["prefix+n", "alt+right"]

# Sessions -> workspaces
new_workspace = "prefix+shift+c"
rename_workspace = "prefix+shift+r"
close_workspace = "prefix+shift+ctrl+x"
previous_workspace = ["prefix+shift+p", "alt+up", "prefix+("]
next_workspace = ["prefix+shift+n", "alt+down", "prefix+)"]

settings = "prefix+shift+s"
goto = ["prefix+g", "prefix+f"]

[[keys.command]]
key = "ctrl+h"
type = "shell"
command = "herdr-nav left"

[[keys.command]]
key = "ctrl+j"
type = "shell"
command = "herdr-nav down"

[[keys.command]]
key = "ctrl+k"
type = "shell"
command = "herdr-nav up"

[[keys.command]]
key = "ctrl+l"
type = "shell"
command = "herdr-nav right"

[[keys.command]]
key = "prefix+s"
type = "popup"
command = "herdr-session-search"
description = "find session"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+t"
type = "popup"
command = "herdr-session-create"
description = "new session from project"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+e"
type = "plugin_action"
command = "chmarax.herdr-nvim.toggle"
description = "nvim sidebar"

[[keys.command]]
key = "prefix+o"
type = "plugin_action"
command = "chmarax.herdr-nvim.pick-file"
description = "open file from agent output"

[ui]
accent = "blue"
sidebar_collapsed_mode = "hidden"
sidebar_start_collapsed=true
hide_tab_bar_when_single_tab=false
tab_bar_position="bottom"

pane_gaps = false
pane_outer_borders = false
pane_scrollbars = false
confirm_close = false
prompt_new_tab_name = false
mouse_capture = true
tab_bar_right = [{ type = "zoom" }, { type = "hostname" }]
window_title = "{hostname}: {workspace}"
