# Overwriting some behaviours for default alias
if command -v eza &> /dev/null; then
  alias ls='eza -lh --group-directories-first --icons=auto --oneline'
  alias lsa='ls -a'
  alias lt='eza --tree --level=2 --icons --git'
  alias lta='lt -a'
fi

alias ff="fzf --preview 'bat --style=numbers --color=always {}'"

alias nvimff='nvim $(ff)'
alias gcb='git branch | fzf --preview "git show --color=always {-1}" |
             cut -c 3- | xargs git checkout'
alias :q='exit'
alias eixt='exit'
alias exp='nautilus'
alias obd='xdg-open obsidian://daily;omarchy-launch-or-focus obsidian'
alias ov='obsidian-vault-search'

# Useful when just after pushing formatting is runing in gh actions
pull () {
  local count=${1:-1}
  for i in $(seq 1 "$count"); do
    output=$(git pull)
    echo "$output"
    if [[ ! "$output" == *"up to date."* ]]; then
      break
    fi
    if [ "$i" -lt "$count" ]; then
      sleep 1  # Not sleeping in last iteration
    fi
  done
}

gce () {
  emojified_text=$(devmoji --text "$1" | sed 's/"/\\"/g')
  git commit -am "$emojified_text"
}

export PATH="$HOME/.tmuxifier/bin:$HOME/.local/bin:$HOME/.spicetify:$PATH"

eval "$(tmuxifier init -)"
