bind-key N split-window -h nvim config
set -g prefix M-Space

# Vim motions in resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Quick split window
bind -n S-Enter split-window -v -c "#{pane_current_path}"
bind -n M-Enter split-window -h -c "#{pane_current_path}"

# Vim motions in navigation
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?|fzf)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

bind-key -T copy-mode-vi 'C-h' send -X cancel \; select-pane -L
bind-key -T copy-mode-vi 'C-j' send -X cancel \; select-pane -D
bind-key -T copy-mode-vi 'C-k' send -X cancel \; select-pane -U
bind-key -T copy-mode-vi 'C-l' send -X cancel \; select-pane -R

bind-key t display-popup -E -w 80% -h 80% "tmux-session-create"
bind-key f display-popup -E -w 80% -h 80% "tmux-window-search"
bind-key s display-popup -E -w 80% -h 80% "tmux-session-search"

# Status bar layout look like pill
set-option -g status-position bottom
set -g status on
set -g status-style "bg=default"
set -g status-justify centre
set -g status-left '#(cat #{socket_path}-\#{session_id}-vimbridge)'
set -g status-right '#(cat #{socket_path}-\#{session_id}-vimbridge-R)'
set -g status-left-length 99
set -g status-right-length 99
set -g focus-events on
# set -g status-left ""
# set -g status-right ""

# Remove separators to allow continuous pill background
set -g window-status-separator ""

# Catppuccin Mocha colors
set -g @active_fg "#1e1e2e"
set -g @active_bg "#cba6f7"
set -g @inactive_fg "#cdd6f4"
set -g @inactive_bg "#45475a"

# Inactive windows
set -g window-status-format "#[fg=#{@inactive_bg},bg=default]#{?#{==:#{window_index},1},,}#[fg=#{@inactive_fg},bg=#{@inactive_bg}] #I #W #[fg=#{@inactive_bg},bg=default]#{?#{==:#{window_index},#{session_windows}},,}"

# Active window
set -g window-status-current-format "#[fg=#{@active_bg},bg=default]#{?#{==:#{window_index},1},,}#[fg=#{@active_fg},bg=#{@active_bg},bold] #I #W #[fg=#{@active_bg},bg=default]#{?#{==:#{window_index},#{session_windows}},,}"
